Opensearch module refactor
sourcefuse/terraform-aws-arc-opensearch pull request #29
Opened 2024-11-05 05:32 UTC by Arunsai14

## Description

Please provide a brief description of the changes introduced by this pull request.

## Related Issue

- [Issue Number](link-to-issue): Brief description

## Checklist

Please ensure that the following steps are completed before submitting the pull request:

- [ ] Code follows the Terraform best practices and style guidelines.
- [ ] Changes are appropriately documented, including any necessary updates to README or other documentation files.
- [ ] Unit tests have been added or updated to cover the changes introduced by this pull request.
- [ ] Changes have been tested locally and verified to work as expected.
- [ ] The code has been reviewed to ensure it aligns with the project's goals and standards.
- [ ] Dependencies and backward compatibility have been considered and addressed if applicable.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Testing Instructions

Provide detailed steps or instructions for testing the changes introduced by this pull request.

## Screenshots

Include any relevant screenshots or visual aids to help reviewers understand the changes visually, if applicable.

## Additional Notes

Add any additional notes or context that might be helpful for reviewers or users testing the changes.

2024-11-06 05:34 UTC, vijay-stephen commented
@Arunsai14 rename non-vpc to public

2024-11-06 05:44 UTC, vijay-stephen requested changes

2024-11-06 05:44 UTC, vijay-stephen commented on variables.tf
>  }
Do we need region variable

2024-11-06 05:44 UTC, vijay-stephen commented on variables.tf
>  }
rename it as `name`

2024-11-06 05:44 UTC, vijay-stephen commented on variables.tf
> +  default     = "m4.large.search"
Please use least type

2024-11-06 05:44 UTC, vijay-stephen commented on variables.tf
> +  default     = 2
Please use 1

2024-11-06 05:44 UTC, vijay-stephen commented on variables.tf
> +  default     = ""
default it as null

2024-11-06 05:44 UTC, vijay-stephen commented on variables.tf
> +  default     = "Policy-Min-TLS-1-2-2019-07"
please use latest policy

2024-11-06 05:44 UTC, vijay-stephen commented on variables.tf
> +}
please use vpc_id variable, check if its value is null

2024-11-06 05:45 UTC, vijay-stephen commented
@Arunsai14 Add serverless option as well

2024-11-07 10:20 UTC, Arunsai14 commented on variables.tf
>  }
correction made

2024-11-07 10:20 UTC, Arunsai14 commented on variables.tf
> +  default     = "m4.large.search"
correction made

2024-11-08 10:26 UTC, manikanta-sadurla approved these changes

2024-11-08 10:35 UTC, siddharth-singh1 approved these changes

2024-11-08 14:05 UTC, tsaucier-sf approved these changes

2024-11-14 10:32 UTC, vijay-stephen approved these changes

2024-11-14 10:33 UTC, merged